#!/usr/bin/env bash
# Deploy the Cosmos DB HPK test infrastructure and write ../.env for the clients.
#
# Requires the `az` CLI to be callable. NOTE: a zsh *alias/function* (e.g. a docker
# wrapper) is NOT visible inside this bash script. Either install a native az
# (`brew install azure-cli`) or export an `AZ` command, e.g.:
#   AZ='docker run --rm -i -v $HOME/.azure:/root/.azure -v $PWD:/workdir -w /workdir mcr.microsoft.com/azure-cli az' ./deploy.sh
set -euo pipefail

AZ="${AZ:-az}"
RG="${RG:-rg-cosmos-hpk-test}"
LOCATION="${LOCATION:-australiaeast}"
DEPLOY_NAME="cosmos-hpk"

# All tunables default to the PUBLISHED run and can be overridden via the environment,
# e.g.  COSMOS_MAX_THROUGHPUT=20000 GEN_ORDERS_PER_DAY=200 ./infra/deploy.sh  (cheaper run).
# deploy.sh bakes these into the generated .env so the generator + clients pick them up.
MAX_THROUGHPUT="${COSMOS_MAX_THROUGHPUT:-100000}"   # RU/s at load; ~10k per physical partition
GEN_START_DATE="${GEN_START_DATE:-2024-01-01}"
GEN_NUM_DAYS="${GEN_NUM_DAYS:-1000}"
GEN_ORDERS_PER_DAY="${GEN_ORDERS_PER_DAY:-1000}"
GEN_BATCH_SIZE="${GEN_BATCH_SIZE:-1000}"
GEN_BUSY_MONTH="${GEN_BUSY_MONTH:-true}"
GEN_BUSY_MONTH_MULT="${GEN_BUSY_MONTH_MULT:-10}"
SWEEP_MAX_CONCURRENCY="${SWEEP_MAX_CONCURRENCY:-6}"
CELL_SECONDS="${CELL_SECONDS:-10}"
TARGET_MAX="${TARGET_MAX:-10000}"                   # idle floor after scale-down

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! $AZ version >/dev/null 2>&1; then
  echo "ERROR: '$AZ' is not callable. Install azure-cli or set AZ=... (see header)." >&2
  exit 1
fi

echo ">> Ensuring resource group '$RG' in '$LOCATION'..."
$AZ group create -n "$RG" -l "$LOCATION" -o none

echo ">> Deploying Bicep at maxThroughput=$MAX_THROUGHPUT RU/s (~$((MAX_THROUGHPUT/10000)) physical partitions)."
echo "   This can take several minutes. High throughput bills more while it is up — the"
echo "   generator runs quickly, then scale-down.sh drops it to $TARGET_MAX RU/s."
$AZ deployment group create \
  -g "$RG" -n "$DEPLOY_NAME" \
  --template-file main.bicep \
  --parameters @main.parameters.json \
  --parameters maxThroughput="$MAX_THROUGHPUT" \
  -o none

echo ">> Reading deployment outputs..."
ACCOUNT=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.accountName.value' -o tsv)
ENDPOINT=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.endpoint.value' -o tsv)
DB=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.databaseName.value' -o tsv)
CONTAINER=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.containerName.value' -o tsv)
KEY=$($AZ cosmosdb keys list -g "$RG" -n "$ACCOUNT" --query primaryMasterKey -o tsv)

ENV_FILE="$SCRIPT_DIR/../.env"
echo ">> Writing $ENV_FILE (pre-filled with published-run values — no manual edit needed)"
cat > "$ENV_FILE" <<EOF
# Generated by infra/deploy.sh. Do NOT commit (holds the primary key).
# Values below reproduce the published ~1.27M-doc / 10-partition run.
COSMOS_ENDPOINT=$ENDPOINT
COSMOS_KEY=$KEY
COSMOS_DATABASE=$DB
COSMOS_CONTAINER=$CONTAINER

# Used by scale-down.sh / teardown.sh
COSMOS_ACCOUNT=$ACCOUNT
COSMOS_RG=$RG
COSMOS_MAX_THROUGHPUT=$MAX_THROUGHPUT

# Data generator knobs
GEN_START_DATE=$GEN_START_DATE
GEN_NUM_DAYS=$GEN_NUM_DAYS
GEN_ORDERS_PER_DAY=$GEN_ORDERS_PER_DAY
GEN_BATCH_SIZE=$GEN_BATCH_SIZE
GEN_BUSY_MONTH=$GEN_BUSY_MONTH
GEN_BUSY_MONTH_MULT=$GEN_BUSY_MONTH_MULT
GEN_AUTOSCALE_MAX=$MAX_THROUGHPUT

# Query client knobs
SWEEP_MAX_CONCURRENCY=$SWEEP_MAX_CONCURRENCY
CELL_SECONDS=$CELL_SECONDS

# Scale-down floor (infra/scale-down.sh)
TARGET_MAX=$TARGET_MAX
EOF

echo ""
echo "Done. Account: $ACCOUNT"
echo "Endpoint:    $ENDPOINT"
echo "Next: ./run-all.sh  (or, individually: generate -> scale-down -> query x2 -> report)"
