#!/usr/bin/env bash
# Deploy the Cosmos DB HPK test infrastructure and write ../.env for the clients.
#
# Requires the `az` CLI to be callable. NOTE: a zsh *alias/function* (e.g. a docker
# wrapper) is NOT visible inside this bash script. Either install a native az
# (`brew install azure-cli`) or export an `AZ` command, e.g.:
#   AZ='docker run --rm -i -v $HOME/.azure:/root/.azure -v $PWD:/workdir -w /workdir mcr.microsoft.com/azure-cli az' ./deploy.sh
set -euo pipefail

AZ="${AZ:-az}"
RG="${RG:-rg-cosmos-hpk-test}"
LOCATION="${LOCATION:-australiaeast}"
DEPLOY_NAME="cosmos-hpk"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! $AZ version >/dev/null 2>&1; then
  echo "ERROR: '$AZ' is not callable. Install azure-cli or set AZ=... (see header)." >&2
  exit 1
fi

echo ">> Ensuring resource group '$RG' in '$LOCATION'..."
$AZ group create -n "$RG" -l "$LOCATION" -o none

echo ">> Deploying Bicep (this creates the account and can take several minutes)..."
$AZ deployment group create \
  -g "$RG" -n "$DEPLOY_NAME" \
  --template-file main.bicep \
  --parameters @main.parameters.json \
  -o none

echo ">> Reading deployment outputs..."
ACCOUNT=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.accountName.value' -o tsv)
ENDPOINT=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.endpoint.value' -o tsv)
DB=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.databaseName.value' -o tsv)
CONTAINER=$($AZ deployment group show -g "$RG" -n "$DEPLOY_NAME" --query 'properties.outputs.containerName.value' -o tsv)
KEY=$($AZ cosmosdb keys list -g "$RG" -n "$ACCOUNT" --query primaryMasterKey -o tsv)

ENV_FILE="$SCRIPT_DIR/../.env"
echo ">> Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Generated by infra/deploy.sh. Do not commit.
COSMOS_ENDPOINT=$ENDPOINT
COSMOS_KEY=$KEY
COSMOS_DATABASE=$DB
COSMOS_CONTAINER=$CONTAINER

# Used by scale-down.sh / teardown.sh
COSMOS_ACCOUNT=$ACCOUNT
COSMOS_RG=$RG

# Data generator knobs
GEN_START_DATE=2024-01-01
GEN_NUM_DAYS=1000
GEN_ORDERS_PER_DAY=500
GEN_BATCH_SIZE=1000
GEN_BUSY_MONTH=true

# Query client knobs
QUERY_ITERATIONS=5
QUERY_WARMUP=1
EOF

echo ""
echo "Done. Account: $ACCOUNT"
echo "Endpoint:    $ENDPOINT"
echo "Next: cd ../src/DataGenerator && dotnet run   (then ../../infra/scale-down.sh)"
